modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="born_in_chaos_v1"
version="1.0.0"
displayName="Born in Chaos "
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Mongoose_artist, MCreator"
description="Adds a lot of hostile mobs, with their own characteristics that can complicate your survival"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.born_in_chaos_v1]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"


[[dependencies.born_in_chaos_v1]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.born_in_chaos_v1]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

