PlayerEvents.loggedIn(event => {
    // Check if the player is joining for the first time
    if (!event.player.stages.has('first_join')) {
        // Grant the player their first join rewards
        let player = event.player

        // Mark the player as having received the first join rewards
        player.stages.add('first_join')

        // Create a bundle and add items to it
        let bundle = Item.of('minecraft:bundle', {
            Items: [
                {id: 'minecraft:stone_pickaxe', Count: 1},
                {id: 'minecraft:stone_axe', Count: 1},
                {id: 'minecraft:stone_shovel', Count: 1},
                {id: 'minecraft:stone_hoe', Count: 1},
                {id: 'minecraft:stone_sword', Count: 1},
                {id: 'minecraft:torch', Count: 8},
                {id: 'minecraft:bread', Count: 9}
            ]
        })

        // Add the bundle to the player's inventory
        player.give(bundle)

        // Add a random artifact item from the Artifacts mod
        let artifacts = [
			'quark:backpack',
            'artifacts:anglers_hat',
            'artifacts:antidote_vessel',
            'artifacts:aqua_dashers',
            'artifacts:bunny_hoppers',
            'artifacts:charm_of_sinking',
            'artifacts:chorus_totem',
            'artifacts:cloud_in_a_bottle',
            'artifacts:cowboy_hat',
            'artifacts:cross_necklace',
            'artifacts:crystal_heart',
            'artifacts:digging_claws',
            'artifacts:eternal_steak',
            'artifacts:everlasting_beef',
            'artifacts:feral_claws',
            'artifacts:fire_gauntlet',
            'artifacts:flame_pendant',
            'artifacts:flippers',
            'artifacts:golden_hook',
            'artifacts:helium_flamingo',
            'artifacts:kitty_slippers',
            'artifacts:lucky_scarf',
            'artifacts:mimic_spawn_egg',
            'artifacts:night_vision_goggles',
            'artifacts:novelty_drinking_hat',
            'artifacts:obsidian_skull',
            'artifacts:onion_ring',
            'artifacts:panic_necklace',
            'artifacts:pickaxe_heater',
            'artifacts:plastic_drinking_hat',
            'artifacts:pocket_piston',
            'artifacts:power_glove',
            'artifacts:rooted_boots',
            'artifacts:running_shoes',
            'artifacts:scarf_of_invisibility',
            'artifacts:shock_pendant',
            'artifacts:snorkel',
            'artifacts:snowshoes',
            'artifacts:steadfast_spikes',
            'artifacts:superstitious_hat',
            'artifacts:thorn_pendant',
            'artifacts:umbrella',
            'artifacts:universal_attractor',
            'artifacts:vampiric_glove',
            'artifacts:villager_hat',
            'artifacts:whoopee_cushion',
            //'celestial_artifacts:abyss_core',
            //'celestial_artifacts:abyss_will_badge',
            'celestial_artifacts:amethyst_ring',
            'celestial_artifacts:angel_heart',
            'celestial_artifacts:angel_pearl',
            'celestial_artifacts:backtrack_mirror',
            'celestial_artifacts:bearing_stamen',
            //'celestial_artifacts:catastrophe_scroll',
            //'celestial_artifacts:chaotic_etching',
            //'celestial_artifacts:chaotic_pendant',
            'celestial_artifacts:charming_bracelet',
            //'celestial_artifacts:corrupt_badge',
            'celestial_artifacts:cross_necklace',
            'celestial_artifacts:cursed_protector',
            //'celestial_artifacts:cursed_talisman',
            //'celestial_artifacts:cursed_totem',
            //'celestial_artifacts:demon_curse',
            //'celestial_artifacts:demon_heart',
            //'celestial_artifacts:desire_etching',
            'celestial_artifacts:destroyer_badge',
            'celestial_artifacts:diamond_ring',
            'celestial_artifacts:earth_axe',
            'celestial_artifacts:earth_hoe',
            'celestial_artifacts:earth_pickaxe',
            'celestial_artifacts:earth_shovel',
            'celestial_artifacts:emerald_bracelet',
            'celestial_artifacts:emerald_necklace',
            'celestial_artifacts:emerald_ring',
            //'celestial_artifacts:ender_protector',
            //'celestial_artifacts:end_etching',
            'celestial_artifacts:evil_eye',
            'celestial_artifacts:fang_necklace',
            'celestial_artifacts:flame_arrow_bag',
            'celestial_artifacts:flight_ring',
            'celestial_artifacts:freeze_ring',
            'celestial_artifacts:gallop_necklace',
            'celestial_artifacts:gluttony_badge',
            'celestial_artifacts:gold_ring',
            //'celestial_artifacts:greedy_heart',
            'celestial_artifacts:guardian_eye',
            'celestial_artifacts:heart_of_revenge',
            //'celestial_artifacts:heirloom_necklace',
            //'celestial_artifacts:hidden_bracelet',
            'celestial_artifacts:holy_necklace',
            'celestial_artifacts:holy_sword',
            'celestial_artifacts:holy_talisman',
            'celestial_artifacts:iron_scabbard',
            'celestial_artifacts:knight_shelter',
            'celestial_artifacts:leech_scabbard',
            'celestial_artifacts:life_bracelet',
            //'celestial_artifacts:life_etching',
            //'celestial_artifacts:lock_of_abyss',
            'celestial_artifacts:magic_arrow_bag',
            'celestial_artifacts:magic_horseshoe',
            'celestial_artifacts:nebula_cube',
            'celestial_artifacts:netherite_ring',
            'celestial_artifacts:nether_fire',
            //'celestial_artifacts:nihility_etching',
            //'celestial_artifacts:origin_etching',
            'celestial_artifacts:prayer_crown',
            'celestial_artifacts:precious_bracelet',
            'celestial_artifacts:precious_necklace',
            'celestial_artifacts:purified_powder',
            'celestial_artifacts:red_heart_necklace',
            'celestial_artifacts:red_ruby_bracelet',
            'celestial_artifacts:repent_mirror',
            'celestial_artifacts:ring_of_life',
            //'celestial_artifacts:sacrificial_object',
            'celestial_artifacts:sands_talisman',
            //'celestial_artifacts:scarlet_bracelet',
            'celestial_artifacts:sea_god_crown',
            'celestial_artifacts:sea_god_scroll',
            //'celestial_artifacts:shadow_pendant',
            'celestial_artifacts:skywalker_scroll',
            'celestial_artifacts:solar_magnet',
            //'celestial_artifacts:soul_box',
            'celestial_artifacts:spirit_arrow_bag',
            'celestial_artifacts:spirit_bracelet',
            'celestial_artifacts:spirit_crown',
            'celestial_artifacts:spirit_necklace',
            'celestial_artifacts:star_necklace',
            //'celestial_artifacts:the_end_dust',
            'celestial_artifacts:thunder_ring',
            'celestial_artifacts:titan_scabbard',
            'celestial_artifacts:traveler_scroll',
            //'celestial_artifacts:truth_etching',
            //'celestial_artifacts:twisted_brain',
            //'celestial_artifacts:twisted_heart',
            //'celestial_artifacts:twisted_scabbard',
            //'celestial_artifacts:twisted_scroll',
            //'celestial_artifacts:undead_charm',
            'celestial_artifacts:unlucky_potato',
            'celestial_artifacts:unowned_pendant',
            //'celestial_artifacts:war_dead_badge',
            'nameless_trinkets:amphibious_hands',
            'nameless_trinkets:blaze_nucleus',
            'nameless_trinkets:blindfold',
            'nameless_trinkets:broken_ankh',
            'nameless_trinkets:broken_magnet',
            'nameless_trinkets:callus',
            'nameless_trinkets:cracked_crown',
            'nameless_trinkets:creeper_sense',
            'nameless_trinkets:dark_nelumbo',
            'nameless_trinkets:dragons_eye',
            //'nameless_trinkets:dubious_dust',
            'nameless_trinkets:electric_paddle',
            'nameless_trinkets:ethereal_wings',
            'nameless_trinkets:experience_battery',
            'nameless_trinkets:experience_magnet',
            'nameless_trinkets:explosion_proof_jacket',
            'nameless_trinkets:fate_emerald',
            'nameless_trinkets:fertilizer',
            'nameless_trinkets:four_leaf_clover',
            'nameless_trinkets:fractured_nullstone',
            'nameless_trinkets:fragile_cloud',
            'nameless_trinkets:ghast_eye',
            'nameless_trinkets:gills',
            //'nameless_trinkets:glowing_dust',
            'nameless_trinkets:gods_crown',
            'nameless_trinkets:ice_cube',
            'nameless_trinkets:light_gloves',
            'nameless_trinkets:lucky_rock',
            'nameless_trinkets:miners_soul',
            'nameless_trinkets:missing_page',
            'nameless_trinkets:moon_stone',
            'nameless_trinkets:mysterious_trinket',
            'nameless_trinkets:nelumbo',
            'nameless_trinkets:pocket_lightning_rod',
            'nameless_trinkets:puffer_fish_liver',
            'nameless_trinkets:rage_mind',
            'nameless_trinkets:reforger',
            'nameless_trinkets:reverse_card',
            'nameless_trinkets:scarab_amulet',
            'nameless_trinkets:sigil_of_baphomet',
            'nameless_trinkets:sleeping_pills',
            'nameless_trinkets:speed_force',
            'nameless_trinkets:spider_legs',
            'nameless_trinkets:super_magnet',
            'nameless_trinkets:tear_of_the_sea',
            'nameless_trinkets:tick',
            'nameless_trinkets:true_heart_of_the_sea',
            //'nameless_trinkets:ultimate_dust',
            'nameless_trinkets:unknown_fragment',
            'nameless_trinkets:vampire_blood',
            'nameless_trinkets:what_magnet',
            'nameless_trinkets:wooden_stick'
        ]

        let randomArtifact = artifacts[Math.floor(Math.random() * artifacts.length)]
        player.give(randomArtifact);
    }
})