modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="better_ore_generation"
version="1.7.2"
displayName="Better Ore Generation"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Kingpvz, MCreator"
description="Makes ore generation much better!"

[[dependencies.better_ore_generation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




