#Server configuration settings
[server]
	#The minimum follow range for hostile mobs
	#Only overridden if the original mob's follow range was lower
	#Default value: 32. Vanilla behaviour: 16
	#Range: 0.0 ~ 2048.0
	minHostileFollowRange = 32.0
	#A list of follow range overrides. Entry format: "mod:entity_id,range"
	#Example: ["minecraft:creeper,32","minecraft:zombie,16"]
	#Default value: ["minecraft:spider,10", "minecraft:cave_spider,10", "minecraft:creeper,12", "minecraft:zombie,16", "minecraft:zombie,16", "minecraft:witch,16", "minecraft:enderman,16", "quark:forgotten,20", "minecraft:wither_skeleton,20", "zombie_extreme:infected,16", "zombie_extreme:runner,16", "zombie_extreme:boomer,16", "zombie_extreme:crawler,16", "zombie_extreme:demolisher,16", "zombie_extreme:clicker,16", "zombie_extreme:inflated,16", "zombie_extreme:faceless,16", "zombie_extreme:goon,16", "zombie_extreme:revived,16", "zombie_extreme:divided,16", "zombie_extreme:parasite,16", "zombie_extreme:zero_patient,16", "zombie_extreme:military,16", "zombie_extreme:assasin_black_ops,16", "minecraft:skeleton,20", "alexscaves:watcher,20", "world_of_rot:blind_walker,10", "mutantmonsters:mutant_zombie,20", "mutantmonsters:mutant_skeleton,36"]
	mobFollowRangeOverrides = [
	"minecraft:blaze,20",
	"minecraft:cave_spider,10",
	"minecraft:creeper,12",
	"minecraft:drowned,20",
	"minecraft:elder_guardian,20",
	"minecraft:ender_dragon,20",
	"minecraft:enderman,20",
	"minecraft:endermite,20",
	"minecraft:evoker,20",
	"minecraft:evoker_fangs,20",
	"minecraft:ghast,20",
	"minecraft:giant,20",
	"minecraft:guardian,20",
	"minecraft:hoglin,20",
	"minecraft:husk,20",
	"minecraft:illusioner,20",
	"minecraft:magma_cube,20",
	"minecraft:phantom,20",
	"minecraft:piglin,20",
	"minecraft:piglin_brute,20",
	"minecraft:pillager,20",
	"minecraft:ravager,20",
	"minecraft:shulker,20",
	"minecraft:shulker_bullet,20",
	"minecraft:silverfish,20",
	"minecraft:skeleton,20",
	"minecraft:skeleton_horse,20",
	"minecraft:slime,20",
	"minecraft:spider,10",
	"minecraft:stray,20",
	"minecraft:vex,20",
	"minecraft:vindicator,20",
	"minecraft:warden,20",
	"minecraft:witch,16",
	"minecraft:wither,20",
	"minecraft:wither_skeleton,20",
	"minecraft:zoglin,20",
	"minecraft:zombie,16",
	"minecraft:zombie_horse,20",
	"minecraft:zombie_villager,20",
	"minecraft:zombified_piglin,20",
	"guardvillagers:guard,20",
	"mutantsbuff:shockwaves,20",
	"mutantsbuff:shockwave,20",
	"mutantsbuff:invul,20",
	"mutantsbuff:explosion,20",
	"mutantsbuff:stable_explosion,20",
	"hordes:zombie_player,20",
	"hordes:husk_player,20",
	"hordes:drowned_player,20",
	"world_of_rot:blind_walker,20",
	"world_of_rot:crawler,20",
	"world_of_rot:burster,20",
	"enhancedai:thrown_web,20",
	"mutantmonsters:creeper_minion,20",
	"mutantmonsters:mutant_creeper,20",
	"mutantmonsters:mutant_enderman,20",
	"mutantmonsters:mutant_skeleton,20",
	"mutantmonsters:mutant_snow_golem,20",
	"mutantmonsters:mutant_zombie,20",
	"mutantmonsters:spider_pig,20",
	"mutantmonsters:body_part,20",
	"mutantmonsters:creeper_minion_egg,20",
	"mutantmonsters:endersoul_clone,20",
	"mutantmonsters:endersoul_fragment,20",
	"mutantmonsters:throwable_block,20",
	"mutantmonsters:mutant_arrow,20",
	"mutantmonsters:skull_spirit,20",
	"wrd:the_angry_giant_king,20",
	"wrd:the_overseer,20",
	"wrd:the_overseer_stage_3,20",
	"wrd:bloodwand_mage_minion,20",
	"wrd:king_snake_body,20",
	"wrd:crystal_spider_minion,20",
	"wrd:wesley,20",
	"wrd:kingsnake_trap,20",
	"wrd:kingsnake_body_trap,20",
	"wrd:the_giant_king,20",
	"wrd:corrupted_zombie,20",
	"wrd:corrupted_skeleton,20",
	"wrd:corrupted_enderman,20",
	"wrd:corrupted_enderman_ghost,20",
	"wrd:corrupted_iron_golem,20",
	"wrd:corrupted_guardling,20",
	"wrd:corrupted_blaze,20",
	"wrd:doom_bot_charge,20",
	"wrd:doom_bot_fire,20",
	"wrd:doom_bot_teleport,20",
	"wrd:petrified_skeletonm,20",
	"wrd:speared_petrified_skeleton_m,20",
	"wrd:dirty_skeleton,20",
	"wrd:mini_ancient_golem,20",
	"wrd:ancient_guard_ling,20",
	"wrd:ancient_guardling_2,20",
	"wrd:small_ant,20",
	"wrd:ancient_fish_golem,20",
	"wrd:dungeon_locator,20",
	"wrd:buff_zombie,20",
	"wrd:the_sad_king,20",
	"wrd:bloody_skeleton,20",
	"wrd:endervillager,20",
	"wrd:ender_peasant,20",
	"wrd:ender_miner,20",
	"wrd:infected_ender_peasant,20",
	"wrd:ender_stinger,20",
	"wrd:ender_enforcer,20",
	"wrd:ender_occultist,20",
	"wrd:ender_leach,20",
	"wrd:ender_king,20",
	"wrd:super_ender_enforcer,20",
	"wrd:heart_of_ender,20",
	"wrd:infected_ender_peasant_minion,20",
	"wrd:ender_stinger_minion,20",
	"wrd:bloodwand_mage,20",
	"wrd:impaled_mage,20",
	"wrd:undead_spider,20",
	"wrd:wall_flower,20",
	"wrd:bait_snapper,20",
	"wrd:hanging_flower,20",
	"wrd:bamboo_mace_cultist,20",
	"wrd:blowdart_cultist,20",
	"wrd:skull_wielding_cultist,20",
	"wrd:coral_drowned,20",
	"wrd:coral_sword_drowned,20",
	"wrd:explosive_drowned,20",
	"wrd:zombie_pharao,20",
	"wrd:zombie_pharao_comunicator,20",
	"wrd:zombie_warrior_pharao,20",
	"wrd:antlion,20",
	"wrd:pharao_wraith,20",
	"wrd:burnt_zombie_pharao,20",
	"wrd:burnt_zombie_pharao_warrior,20",
	"wrd:burnt_pharao_comunicator,20",
	"wrd:yeti,20",
	"wrd:frost_golem,20",
	"wrd:frost_soldier,20",
	"wrd:frost_guard,20",
	"wrd:frost_exploder,20",
	"wrd:frost_mage,20",
	"wrd:broken_frost_golem,20",
	"wrd:broken_frost_soldier,20",
	"wrd:broken_frost_guard,20",
	"wrd:broken_frost_exploder,20",
	"wrd:icy_spirit,20",
	"wrd:blackstone_blaze,20",
	"wrd:shielded_blackstone_blaze,20",
	"wrd:supreme_blackstone_blaze,20",
	"wrd:hateful_spirit,20",
	"wrd:lesser_hateful_spirit,20",
	"wrd:crimson_piglin,20",
	"wrd:crimson_wither_skeleton,20",
	"wrd:strider_worker,20",
	"wrd:strider_guard,20",
	"wrd:forge_golem,20",
	"wrd:crimson_ressurector,20",
	"wrd:forsaken_cultist_exploder,20",
	"wrd:forsaken_cultist_empowerer,20",
	"wrd:forsaken_cultist_summoner,20",
	"wrd:mutated_brute,20",
	"wrd:illager_occultist,20",
	"wrd:illager_trapper,20",
	"wrd:monsterous_book,20",
	"wrd:ancient_skeleton_skull,20",
	"wrd:ancient_skeleton_torso,20",
	"wrd:ancient_skeleton,20",
	"wrd:loosey,20",
	"wrd:loosey_headless,20",
	"wrd:bulky_ancient_skeleton,20",
	"wrd:bulky_ancient_skeleton_torso,20",
	"wrd:cursed_cultist,20",
	"wrd:cursed_cultist_healer,20",
	"wrd:mini_demon,20",
	"wrd:cursed_sorcerer,20",
	"wrd:cursed_demon,20",
	"wrd:cursed_eye_demon,20",
	"wrd:king_snake,20",
	"wrd:dark_shop_keeper,20",
	"wrd:dungeon_coral_drowned,20",
	"wrd:dungeon_coral_sword_drowned,20",
	"wrd:dungeon_explosive_drowned,20",
	"wrd:aqua_guard,20",
	"wrd:crystal_spider,20",
	"wrd:crawling_eye,20",
	"wrd:faceof_the_maw,20",
	"wrd:the_corpse,20",
	"wrd:undead_architect,20",
	"wrd:armored_undead_architect,20",
	"wrd:dead_wall_flower,20",
	"wrd:dead_bait_snapper,20",
	"wrd:dead_hanging_flower,20",
	"wrd:the_beyond,20",
	"wrd:architect,20",
	"wrd:armored_architect,20",
	"wrd:hooded_architect,20",
	"wrd:crowned_architect,20",
	"wrd:friendly_undead_architect,20",
	"wrd:final_boss_phase_1,20",
	"wrd:armored_architect_minion,20",
	"wrd:hooded_architect_minion,20",
	"wrd:crowned_architect_minion,20",
	"wrd:final_boss_phase_2,20",
	"wrd:final_boss_phase_3,20",
	"wrd:final_boss_phase_4,20",
	"wrd:final_boss_phase_5,20",
	"wrd:the_fallen,20",
	"wrd:projectile_corrupted_great_scepter,20",
	"wrd:projectile_throwable_bomb,20",
	"wrd:projectile_blood_wand,20",
	"wrd:projectile_spear,20",
	"wrd:projectile_blowdart,20",
	"wrd:projectile_rooted_spear,20",
	"wrd:projectile_pharao_wand,20",
	"wrd:projectile_throwable_icicle,20",
	"wrd:projectile_ice_wand,20",
	"wrd:projectile_throwable_ice_bomb,20",
	"wrd:projectile_ice_spear,20",
	"wrd:projectile_throwable_firebomb,20",
	"wrd:projectile_death_tome,20",
	"wrd:projectile_acid_wand,20",
	"wrd:puddle_spawn,20",
	"wrd:miniseer,20",
	"wrd:the_overseer_stage_2,20",
	"wrd:rolling_boulder,20",
	"wrd:rolling_bouler_x_minus,20",
	"wrd:rolling_boulder_zplus,20",
	"wrd:rolling_boulder_z_minus,20",
	"wrd:rotating_spike_trap,20",
	"wrd:ghosthead,20",
	"wrd:rotating_pentagram,20",
	"wrd:rotating_green_pentagram,20",
	"wrd:rotating_blue_pentagram,20",
	"wrd:rotating_green_pentagram_friendly,20",
	"wrd:rotating_green_pentagram_undead,20",
	"wrd:ghosthead_finalboss,20",
	"wrd:rotating_green_pentagram_minion,20",
	"wrd:rotating_green_pentagram_random_architect,20",
	"wrd:rotating_pentagram_x,20",
	"wrd:rotating_pentagram_z,20",
	"wrd:rotating_pentagram_xm,20",
	"wrd:rotating_pentagram_zm,20",
	"wrd:falling_block_entity,20",
	"wrd:falling_chandilier_entity,20",
	"wrd:undead_mage,20",
	"wrd:projectile_undead_mage_projectile,20",
	"wrd:undead_mage_stage_2,20",
	"wrd:undead_mage_stage_3,20",
	"wrd:dirtyskeleton_2,20",
	"wrd:dirtyskeleton_3,20",
	"wrd:dirtyskeleton_4,20",
	"wrd:necromancer_stage_1,20",
	"wrd:necromancer_stage_2,20",
	"wrd:necromancer_stage_3,20",
	"wrd:ancient_golem_stage_1,20",
	"wrd:ancient_golem_stage_2,20",
	"wrd:ancient_golem_stage_3,20",
	"wrd:poison_drop,20",
	"wrd:ancient_guardian,20",
	"wrd:guardian_bomb,20",
	"wrd:mummy_stage_1,20",
	"wrd:mummy_stage_2,20",
	"wrd:mummy_stage_3,20",
	"wrd:wraith,20",
	"wrd:the_host,20",
	"wrd:flesh_bomb,20",
	"wrd:king_wraith,20",
	"wrd:heart_of_ice,20",
	"wrd:heart_of_ice_2,20",
	"wrd:heart_of_ice_3,20",
	"wrd:heart_of_ice_companion,20",
	"wrd:ice_mage_stage_1,20",
	"wrd:ice_mage_stage_2,20",
	"wrd:ice_mage_stage_3,20",
	"wrd:projectile_ice_mage_projectile,20",
	"wrd:doompillar_mob,20",
	"wrd:doom_golem_1,20",
	"wrd:doom_golem_2,20",
	"wrd:doom_golem_3,20",
	"wrd:soul_bomb,20",
	"wrd:enemyspike,20",
	"wrd:enemy_currupted_spike,20",
	"wrd:projectile_corrupted_blaze_projectile,20",
	"wrd:projectile_magic_spellbook,20",
	"wrd:projectile_the_angry_giant_king_projectile,20",
	"wrd:projectile_heart_of_ender_projectile,20",
	"wrd:projectile_charged_relic_of_souls,20",
	"wrd:hidden_undead_spider,20",
	"wrd:petrified_skeleton_minion,20",
	"wrd:speared_petrified_skeleton_minion,20",
	"wrd:impaled_mage_minion,20",
	"wrd:bait_snapper_closed,20",
	"wrd:projectile_acid_projectile,20",
	"wrd:wall_flower_2,20",
	"wrd:ranged_antlion,20",
	"wrd:projectile_antlion_projectile,20",
	"wrd:burried_antlion,20",
	"wrd:falling_icicle_mob,20",
	"wrd:projectile_frostguard_spear,20",
	"wrd:unconscious_crimson_piglin,20",
	"wrd:unconscious_wither_skeleton,20",
	"wrd:broken_crimson_ressurector,20",
	"wrd:projectile_blood_projectile,20",
	"wrd:magic_trap,20",
	"wrd:projectile_loosey_projectile,20",
	"wrd:broken_cursed_cultist,20",
	"wrd:natural_infinite_dungeon_spawns,20",
	"wrd:giant_mummy,20",
	"wrd:giant_mummy_arm,20",
	"wrd:enemy_bloody_spike,20",
	"wrd:dead_wall_flower_2,20",
	"wrd:dead_baitsnapper_closed,20",
	"wrd:projectile_blood_plant_projectile,20",
	"wrd:projectile_debug_pentagram_particle,20",
	"wrd:projectile_corrupted_great_sceptre,20",
	"wrd:projectile_exploding_corrupted_projectile,20",
	"wrd:projectile_final_boss_undead_spawn_projectile,20",
	"wrd:projectile_final_boss_final_projectile,20",
	"zombie_extreme:projectile_spit_inflated,20",
	"zombie_extreme:infected,20",
	"zombie_extreme:runner,20",
	"zombie_extreme:infected_police,20",
	"zombie_extreme:infected_hazmat,20",
	"zombie_extreme:infected_military,20",
	"zombie_extreme:infected_juggernaut,20",
	"zombie_extreme:boomer,20",
	"zombie_extreme:crawler,20",
	"zombie_extreme:demolisher,20",
	"zombie_extreme:ram,20",
	"zombie_extreme:chainsaw,20",
	"zombie_extreme:explosive_infected,20",
	"zombie_extreme:night_hunter,20",
	"zombie_extreme:rat_king,20",
	"zombie_extreme:clicker,20",
	"zombie_extreme:inflated,20",
	"zombie_extreme:faceless,20",
	"zombie_extreme:goon,20",
	"zombie_extreme:revived,20",
	"zombie_extreme:divided,20",
	"zombie_extreme:devestated,20",
	"zombie_extreme:parasite,20",
	"zombie_extreme:zero_patient,20",
	"zombie_extreme:fetus,20",
	"zombie_extreme:military,20",
	"zombie_extreme:assasin_black_ops,20",
	"divine_weaponry:projectile_wooden_shuriken,20",
	"divine_weaponry:projectile_stone_shuriken,20",
	"divine_weaponry:projectile_iron_shuriken,20",
	"divine_weaponry:projectile_golden_shuriken,20",
	"divine_weaponry:projectile_diamond_shuriken,20",
	"divine_weaponry:projectile_netherite_shuriken,20",
	"divine_weaponry:projectile_amaterasu_shuriken,20",
	"divine_weaponry:projectile_item_mjollnirlaunch_shooter,20",
	"divine_weaponry:apophis_follower,20",
	"divine_weaponry:fujin_cloud,20",
	"divine_weaponry:erebus_wither,20",
	"divine_weaponry:ice_wall,20",
	"divine_weaponry:cernunnos_target,20",
	"insanelib:area_effect_cloud_3d,20",
	"alexsmobs:crimson_mosquito,20",
	"alexsmobs:mosquito_spit,20",
	"alexsmobs:rattlesnake,20",
	"alexsmobs:hammerhead_shark,20",
	"alexsmobs:shark_tooth_arrow,20",
	"alexsmobs:centipede_head,20",
	"alexsmobs:centipede_body,20",
	"alexsmobs:centipede_tail,20",
	"alexsmobs:mimicube,20",
	"alexsmobs:soul_vulture,20",
	"alexsmobs:spectre,20",
	"alexsmobs:straddler,20",
	"alexsmobs:stradpole,20",
	"alexsmobs:skreecher,20",
	"alexsmobs:murmur,20",
	"alexsmobs:murmur_head,20",
	"alexsmobs:tendon_segment,20",
	"alexsmobs:fart,20",
	"alexsmobs:cosmic_cod,20",
	"alexsmobs:skelewag,20",
	"alexsmobs:frilled_shark,20",
	"alexsmobs:mimic_octopus,20",
	"alexsmobs:cosmaw,20",
	"alexsmobs:underminer,20",
	"alexsmobs:serpent,20",
	"alexsmobs:void_worm,20",
	"alexsmobs:void_worm_part,20",
	"alexsmobs:void_worm_shot,20",
	"alexsmobs:void_portal,20",
	"alexsmobs:rocky_roller,20",
	"alexsmobs:murmur,20",
	"alexsmobs:murmur_head,20",
	"alexsmobs:tendon_segment,20",
	"alexsmobs:skunk,20",
	"alexsmobs:fart,20",
	"alexsmobs:anaconda,20",
	"alexsmobs:anaconda_part,20",
	"twilightforest:adherent,20",
	"twilightforest:alpha_yeti,20",
	"twilightforest:armored_giant,20",
	"twilightforest:carminite_broodling,20",
	"twilightforest:carminite_ghastguard,20",
	"twilightforest:carminite_ghastling,20",
	"twilightforest:carminite_golem,20",
	"twilightforest:cube_of_annihilation,20",
	"twilightforest:death_tome,20",
	"twilightforest:fire_beetle,20",
	"twilightforest:giant_miner,20",
	"twilightforest:harbinger_cube,20",
	"twilightforest:hedge_spider,20",
	"twilightforest:helmet_crab,20",
	"twilightforest:hostile_wolf,20",
	"twilightforest:hydra,20",
	"twilightforest:hydra_mortar,20",
	"twilightforest:king_spider,20",
	"twilightforest:knight_phantom,20",
	"twilightforest:lich,20",
	"twilightforest:lich_bolt,20",
	"twilightforest:lich_bomb,20",
	"twilightforest:lich_minion,20",
	"twilightforest:lower_goblin_knight,20",
	"twilightforest:loyal_zombie,20",
	"twilightforest:maze_slime,20",
	"twilightforest:minoshroom,20",
	"twilightforest:minotaur,20",
	"twilightforest:mist_wolf,20",
	"twilightforest:moonworm_shot,20",
	"twilightforest:mosquito_swarm,20",
	"twilightforest:naga,20",
	"twilightforest:nature_bolt,20",
	"twilightforest:pinch_beetle,20",
	"twilightforest:plateau_boss,20",
	"twilightforest:rising_zombie,20",
	"twilightforest:roving_cube,20",
	"twilightforest:skeleton_druid,20",
	"twilightforest:slime_beetle,20",
	"twilightforest:slime_blob,20",
	"twilightforest:snow_guardian,20",
	"twilightforest:snow_queen,20",
	"twilightforest:stable_ice_core,20",
	"twilightforest:swarm_spider,20",
	"twilightforest:thrown_block,20",
	"twilightforest:thrown_wep,20",
	"twilightforest:wand_bolt,20",
	"twilightforest:unstable_ice_core,20",
	"twilightforest:upper_goblin_knight,20",
	"twilightforest:ur_ghast,20",
	"twilightforest:winter_wolf,20",
	"twilightforest:wraith,20",
	"twilightforest:yeti,20",
	"riskofrain_mobs:lemurian_entity,20",
	"riskofrain_mobs:stone_golem_entity,20",
	"riskofrain_mobs:gunner_drone_entity,20",
	"riskofrain_mobs:drone_bullet_entity,20",
	"realmrpg_demons:chort,20",
	"realmrpg_demons:imp,20",
	"realmrpg_demons:imp_guard,20",
	"realmrpg_demons:demon,20",
	"realmrpg_demons:demon_lord,20",
	"realmrpg_demons:ancient_demon_lord,20",
	"realmrpg_demons:demon_minion,20",
	"artifacts:mimic,20",
	"alexscaves:teletor,20",
	"alexscaves:boundroid,20",
	"alexscaves:boundroid_winch,20",
	"alexscaves:ferrouslime,20",
	"alexscaves:notor,20",
	"alexscaves:quarry_smasher,20",
	"alexscaves:seeking_arrow,20",
	"alexscaves:subterranodon,20",
	"alexscaves:vallumraptor,20",
	"alexscaves:grottoceratops,20",
	"alexscaves:trilocaris,20",
	"alexscaves:tremorsaurus,20",
	"alexscaves:relicheirus,20",
	"alexscaves:luxtructosaurus,20",
	"alexscaves:tephra,20",
	"alexscaves:atlatitan,20",
	"alexscaves:nucleeper,20",
	"alexscaves:brainiac,20",
	"alexscaves:thrown_waste_drum,20",
	"alexscaves:gammaroach,20",
	"alexscaves:tripodfish,20",
	"alexscaves:deep_one,20",
	"alexscaves:deep_one_knight,20",
	"alexscaves:deep_one_mage,20",
	"alexscaves:water_bolt,20",
	"alexscaves:mine_guardian,20",
	"alexscaves:mine_guardian_anchor,20",
	"alexscaves:floater,20",
	"alexscaves:guano,20",
	"alexscaves:gloomoth,20",
	"alexscaves:underzealot,20",
	"alexscaves:watcher,40",
	"alexscaves:corrodent,20",
	"alexscaves:vesper,20",
	"alexscaves:forsaken,20",
	"alexscaves:beholder_eye,20",
	"alexscaves:desolate_dagger,20",
	"alexscaves:burrowing_arrow,20",
	"alexscaves:dark_arrow,20",
	"quark:foxhound,20",
	"quark:forgotten,20",
	"quark:toretoise,20",
	"quark:wraith,20",
	"supplementaries:red_merchant,20",
	"create_sa:projectile_flamethrower_pr,20",
	"create_sa:projectile_flamethrower_pr_2,20",
	"create_sa:brass_cube_r,20",
	"creeperoverhaul:jungle_creeper,20",
	"creeperoverhaul:bamboo_creeper,20",
	"creeperoverhaul:desert_creeper,20",
	"creeperoverhaul:badlands_creeper,20",
	"creeperoverhaul:hills_creeper,20",
	"creeperoverhaul:savannah_creeper,20",
	"creeperoverhaul:mushroom_creeper,20",
	"creeperoverhaul:swamp_creeper,20",
	"creeperoverhaul:dripstone_creeper,20",
	"creeperoverhaul:cave_creeper,20",
	"creeperoverhaul:dark_oak_creeper,20",
	"creeperoverhaul:spruce_creeper,20",
	"creeperoverhaul:beach_creeper,20",
	"creeperoverhaul:snowy_creeper,20",
	"creeperoverhaul:ocean_creeper,20"]