
#Maximum distance mobs will spawn away from players
[distanceConfig]
	distant = 80

#Maximum height mobs will spawn above or below players
[heightConfig]
	height = 20

#Frequency (in seconds) for chat information updates
[frequencyConfig]
	frequencyChat = 30

#Frequency (in seconds) for mob despawn
[frequencyDespawn]
	frequencyDespawn = 30

#Maximum number of Monster (only hostile mobs) that can be spawned per player
[maxMonsterPerPlayer]
	maxMonsterPerPlayer = 60

#Mobs that will not spawn, example: mobs: ["minecraft:zombie", "minecraft:skeleton"]
[mobsBlocked]
	mobsBlocked = []

#Mobs that will bypass all rules to spawn, example: mobs: ["minecraft:spider", "minecraft:creeper"]
[mobsUnBlocked]
	mobsUnBlocked = []

