
#Maximum distance mobs will spawn away from players
[distanceConfig]
	distant = 60

#Maximum height mobs will spawn above or below players
[heightConfig]
	height = 20

#Frequency (in seconds) for chat information updates
[frequencyConfig]
	frequencyChat = 120

#Frequency (in seconds) for mob despawn
[frequencyDespawn]
	frequencyDespawn = 120

#Maximum number of Monster that can be spawned per player
[maxMonsterPerPlayer]
	maxMonsterPerPlayer = 20

