
[General]
	#If enabled your console will fill with spam showing the various types of data you will need to fine tune this config
	showConsoleIDS = false
	#If selected the rest of the config is pointless. Default: false
	tanningLotion = false
	#Should players burn? Default: false
	burnPlayers = false
	#Should ops NOT burn? Default: true
	noOpBurn = true
	#Allow all of a mods' mobs from burning just by specifying the modid. Comma separated and quoted list
	#Default: "iceandfire"
	mods = ["iceandfire", "zombie_extreme", "mutant_monsters", "mutantmonsters", "riskofrain_mobs", "realmrpg_demons", "duckensinvasion"]
	#Allows specific mods' mobs to burn just by specifying their full id for example modid:mobname.  Comma separated and quoted list
	#Default: "minecraft:zombie","minecraft:skeleton"
	mobs = ["minecraft:zombie", "minecraft:zombie", "minecraft:zombie_villager", "minecraft:zombie_horse", "minecraft:witch", "minecraft:drowned", "minecraft:enderman", "minecraft:slime", "minecraft:husk", "minecraft:cave_spider", "twilightforest:slime_beetle", "minecraft:skeleton", "world_of_rot:blind_walker", "world_of_rot:crawler", "world_of_rot:burster", "realmrpg_demons:chort", "realmrpg_demons:imp", "realmrpg_demons:imp_guard", "realmrpg_demons:demon", "realmrpg_demons:demon_lord"]
	#Allows specific mods' blocks to be ignored while checking if you are able to see the sky by specifying their full id for example modid:blockname.  Comma separated and quoted list
	#Example: "minecraft:black_stained_glass"
	ignoredBlocks = []

