
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true
	#Don't touch unless you are told to
	debug_packet = false

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false

	#Disables certain types
	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.ecologics]
				flowering_azalea = true
				azalea = true
				coconut = true
				walnut = true

			[general.types.wood_type.quark]
				azalea = true
				ancient = true
				blossom = true

			[general.types.wood_type.twilightforest]
				twilight_oak = true
				canopy = true
				mangrove = true
				dark = true
				time = true
				transformation = true
				mining = true
				sorting = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

		[general.types.leaves_type]

			[general.types.leaves_type.twilightforest]
				beanstalk = true
				thorn = true
				twilight_oak = true
				canopy = true
				mangrove = true
				dark = true
				rainbow_oak = true
				time = true
				transformation = true
				mining = true
				sorting = true

			[general.types.leaves_type.ecologics]
				coconut = true
				walnut = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.alexscaves]
				ancient = true

		[general.types.cake]

			[general.types.cake.createaddition]
				chocolate_cake = true
				honey_cake = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.cfm]
				stripped_kitchen_sink_light = true
				table = true
				coffee_table = true
				park_bench = true
				stripped_kitchen_counter = true
				stripped_cabinet = true
				kitchen_drawer = true
				desk = true
				stripped_bedside_cabinet = true
				desk_cabinet = true
				stripped_kitchen_drawer = true
				upgraded_fence = true
				kitchen_sink_dark = true
				stripped_desk_cabinet = true
				kitchen_counter = true
				upgraded_gate = true
				stripped_park_bench = true
				cabinet = true
				stripped_table = true
				mail_box = true
				blinds = true
				stripped_chair = true
				crate = true
				chair = true
				stripped_mail_box = true
				stripped_blinds = true
				stripped_kitchen_sink_dark = true
				bedside_cabinet = true
				stripped_upgraded_fence = true
				stripped_desk = true
				kitchen_sink_light = true
				stripped_coffee_table = true
				stripped_crate = true
				stripped_upgraded_gate = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

			[general.entries.wood_type.quark]
				vertical_planks = true
				chest = true
				ladder = true
				hollow_log = true
				post = true
				trapped_chest = true
				bookshelf = true
				stripped_post = true

			[general.entries.wood_type.twilightforest]
				banister = true
				hollow_log_climbable = true
				hollow_log_horizontal = true
				hollow_log_vertical = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = true

			[general.entries.leaves_type.cfm]
				hedge = true

