
[general]
	#Aptitudes Max Level [default: 32]
	#Range: 2 ~ 1000
	aptitudeMaxLevel = 32
	#First aptitudes level cost: [default: 5]
	#Range: 1 ~ 1000
	aptitudeFirstCostLevel = 1
	#Show potions overlay over skills [default: true]
	showPotionsHud = true
	#Lock item list: (see the wiki if you wanna know how to add a unlock item)
	lockItemList = []

[passives]
	#Attack Damage passive value at max level [default: 1.5]
	#Range: 0.0 ~ 10000.0
	attackDamageValue = 1.5
	#Attack Knockback passive value at max level [default: 0.4]
	#Range: 0.0 ~ 10000.0
	attackKnockbackValue = 0.4
	#Max Health passive value at max level [default: 20.0]
	#Range: 0.0 ~ 10000.0
	maxHealthValue = 20.0
	#Knockback Resistance passive value at max level [default: 0.5]
	#Range: 0.0 ~ 10000.0
	knockbackResistanceValue = 0.5
	#Movement Speed passive value at max level [default: 0.05]
	#Range: 0.0 ~ 10000.0
	movementSpeedValue = 0.05
	#Projectile Damage passive value at max level [default: 5.0]
	#Range: 0.0 ~ 10000.0
	projectileDamageValue = 5.0
	#Armor passive value at max level [default: 4.0]
	#Range: 0.0 ~ 10000.0
	armorValue = 4.0
	#Armor Toughness passive value at max level [default: 1.0]
	#Range: 0.0 ~ 10000.0
	armorToughnessValue = 1.0
	#Attack Speed passive value at max level [default: 0.4]
	#Range: 0.0 ~ 10000.0
	attackSpeedValue = 0.4
	#Entity Reach passive value at max level [default: 1.0]
	#Range: 0.0 ~ 10000.0
	entityReachValue = 1.0
	#Block Reach passive value at max level [default: 1.5]
	#Range: 0.0 ~ 10000.0
	blockReachValue = 1.5
	#Break Speed passive value at max level [default: 0.5]
	#Range: 0.0 ~ 10000.0
	breakSpeedValue = 0.5
	#Beneficial Effect passive value at max level [default: 60.0]
	#Range: 0.0 ~ 10000.0
	beneficialEffectValue = 60.0
	#Magic Resist passive value at max level [default: 0.5]
	#Range: 0.0 ~ 10000.0
	magicResistValue = 0.5
	#Critical Damage passive value at max level [default: 0.25]
	#Range: 0.0 ~ 10000.0
	criticalDamageValue = 0.25
	#Luck passive value at max level [default: 2.0]
	#Range: 0.0 ~ 10000.0
	luckValue = 2.0

[skills]
	#One Handed skill damage amplifier increase [default: 0.5]
	#Range: 0.0 ~ 10000.0
	oneHandedAmplifier = 0.5
	#Fighting Spirit skill strength potion effect boost [default: 1]
	#Range: 1 ~ 255
	fightingSpiritBoost = 1
	#Fighting Spirit skill strength potion effect duration [default: 3]
	#Range: 1 ~ 3600
	fightingSpiritDuration = 3
	#Berserker skill health percent [default: 30]
	#Range: 0 ~ 100
	berserkerPercent = 30
	#Athletics skill air modifier multiply [default: 1.5]
	#Range: 0.0 ~ 500.0
	athleticsModifier = 1.5
	#Lion Heart skill negative potion effect percent [default: 50]
	#Range: 0 ~ 100
	lionHeartPercent = 50
	#Quick Reposition skill speed potion effect boost [default: 2]
	#Range: 1 ~ 255
	quickRepositionBoost = 2
	#Quick Reposition skill speed potion effect duration [default: 3]
	#Range: 1 ~ 3600
	quickRepositionDuration = 3
	#Stealth Mastery skill enemy vision percent [default: 20]
	#Range: 0 ~ 100
	stealthMasteryUnSneakPercent = 20
	#Stealth Mastery skill enemy vision percent when player is sneaking [default: 60]
	#Range: 0 ~ 100
	stealthMasterySneakPercent = 60
	#Stealth Mastery skill arrow damage modifier multiply [default: 1.25]
	#Range: 0.0 ~ 100.0
	stealthMasteryModifier = 1.25
	#Counter Attack skill duration to return the attack [default: 3]
	#Range: 0 ~ 3600
	counterAttackDuration = 3
	#Counter Attack skill damage returned percent [default: 50]
	#Range: 0 ~ 500
	counterAttackPercent = 50
	#Diamond Skin defence potion effect boost [default: 2]
	#Range: 1 ~ 255
	diamondSkinBoost = 2
	#Diamond skill defense amplifier increase when player is sneaking [default: 2.0]
	#Range: 0.0 ~ 10000.0
	diamondSkinSneakAmplifier = 2.0
	#Haggler skill villager trades cost percent reduced [default: 20]
	#Range: 0 ~ 100
	hagglerPercent = 20
	#Expert Alchemist skill potion amplifier increase [default: 1.0]
	#Range: 0.0 ~ 10000.0
	alchemyManipulationAmplifier = 1.0
	#Obsidian Smasher skill obsidian breaking speed modifier multiply [default: 10.0]
	#Range: 0.0 ~ 100.0
	obsidianSmasherModifier = 10.0
	#Treasure Hunter skill probability chance to get a treasure in dirt, example: 1/500 it means that 1 out of every 500 (0,2%) dirt blocks you can get a treasure. [default: 500]
	#Range: 1 ~ 10000
	treasureHunterProbability = 500
	#Treasure Hunter skill treasures item list: (see the wiki if you wanna know how to add a treasure item)
	treasureHunterItemList = []
	#Convergence skill probability chance to obtain part of the spent material, example: 1/8 it means that 1 out of every 8 (12,5%) crafted items you can obtain a part of the spent material. [default: 8]
	#Range: 1 ~ 10000
	convergenceProbability = 8
	#Convergence skill convergence item list: (see the wiki if you wanna know how to add a convergence item)
	convergenceItemList = []
	#Life Eater skill life steal amplifier increase [default: 1.0]
	#Range: 0.0 ~ 10000.0
	lifeEaterModifier = 1.0
	#Critical Roll skill critic modifier multiply when you roll a 6 [default: 1.25]
	#Range: 0.0 ~ 100.0
	criticalRoll6Modifier = 1.25
	#Critical Roll skill critic probability reduce when you roll a 1, example: 1/3 it means that 1 out of every 3 (33%) the critic damage will be reduced. [default: 3]
	#Range: 1 ~ 10000
	criticalRoll1Probability = 3
	#Lucky Drop skill mob drops modifier multiply [default: 2.0]
	#Range: 0.0 ~ 10000.0
	luckyDropModifier = 2.0
	#Lucky Drop skill mobs drops probability, example: 1/5 it means that 1 out of every 5 (20%) the mob drops will be multiplied. [default: 10]
	#Range: 1 ~ 10000
	luckyDropProbability = 10
	#Limit Breaker skill deal damage amplifier [default: 999.0]
	#Range: 0.0 ~ 10000.0
	limitBreakerAmplifier = 999.0
	#Limit Breaker skill deal damage probability, example: 1/100 it means that 1 in 100 (1%) to deal damage amplified. [default: 100]
	#Range: 1 ~ 10000
	limitBreakerProbability = 100

