
[General]
	#Print all found mob IDS to the console, will cause spam
	printIDs = false
	#Protects all mobs from fire
	protectAllMobs = true
	#Protects these mods from fire (any mobs with these namespaces)
	mods = ["iceandfire","minecraft","born_in_chaos_v1"]
	#Protects these mobs from fire (any mobs with these ids (namespace:name))
	mobs = ["minecraft:zombie", "minecraft:drowned", "minecraft:skeleton", "minecraft:stray"]

