
#General configuration settings
[general]
	scaledFallDamage = true
	scaledMotion = false
	scaledReach = false
	scaledAttack = true
	scaledDefense = true
	scaledHealth = true
	scaledItemDrops = true
	scaledProjectiles = true
	scaledExplosions = true
	keepAllScalesOnRespawn = false
	accurateNetherPortals = true
	scalesKeptOnRespawn = []
	enableCommands = true
	enableDebugCommands = true

