modLoader = "javafml"

loaderVersion = "[43,)"

license = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

[[mods]]

modId = "t_and_t"

version = "${file.jarVersion}"

displayName = "Towns and Towers"

authors = "Kubek, Biban_Auriu, Cristelknight"

description = '''
Spice up your world with new villages, pillager outposts, and even new ships!
'''

[[dependencies.t_and_t]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.t_and_t]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.t_and_t]]
modId = "cristellib"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"

